INSERT INTO `CPG_plugin_xfeeds` (
    xfd_rss_button,
	xfd_standard,
	xfd_google,
	xfd_yahoo,
	xfd_msn,
	xfd_lines,
	xfd_aol,
	xfd_feedburn,
	xfd_feedburnuname,
	xfd_feedroute,
	xfd_customenable1,
	xfd_customenable2,
	xfd_customenable3,
	xfd_customenable4,
	xfd_customenable5,
	xfd_customtitle1,
	xfd_customtitle2,
	xfd_customtitle3,
	xfd_customtitle4,
	xfd_customtitle5,
	xfd_customurl1,
	xfd_customurl2,
	xfd_customurl3,
	xfd_customurl4,
	xfd_customurl5,
	xfd_theme,
    xfd_feed_items)
VALUES (
    1,
	1,
	1,
	1,
	1,
	1,
	1,
	0,
	'undefined',
	0,
	0,
	0,
	0,
	0,
	0,
	'Link Title 1',
	'Link Title 2',
	'Link Title 3',
	'Link Title 4',
	'Link Title 5',
	'http://www.example.com',
	'http://www.example.com',
	'http://www.example.com',
	'http://www.example.com',
	'http://www.example.com',
	3,
    10
);