<?php
/*************************
  Coppermine Photo Gallery
  ************************
  Copyright (c) 2003-2009 Coppermine Dev Team
  v1.1 originally written by Gregory DEMAR

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License version 3
  as published by the Free Software Foundation.

  ********************************************
  $HeadURL$
  $Revision$
  $LastChangedBy$
  $Date$
**********************************************/

$lang_plugin_newsletter['config_name'] = 'Newsletter';
$lang_plugin_newsletter['config_description'] = 'Enables your users to subscribe to newsletters. Allows the admin to send newsletters.'; 
$lang_plugin_newsletter['author'] = 'Created by %s';
$lang_plugin_newsletter['drop_table_warning'] = 'Deleting database tables can not be undone (that\'s what each of the above options does)! If you\'re not sure, don\'t check the above options.';
$lang_plugin_newsletter['remove_plugin_warning'] = 'Warning: the newsletters you have sent contain links to the pages generated by the plugin. Removing the plugin will result in broken links for the recipients of your previous mailings, which will look silly.';
$lang_plugin_newsletter['config'] = 'Newsletter Configuration';
$lang_plugin_newsletter['subscribe_to_newsletter'] = 'Subscribe to newsletter';
$lang_plugin_newsletter['remove_config'] = 'Delete configuration?';
$lang_plugin_newsletter['remove_config_explanation'] = 'This will permanently delete the newsletter plugin config options.';
$lang_plugin_newsletter['subscriber_list'] = 'Subscriber List';
$lang_plugin_newsletter['remove_subscribers'] = 'Delete subscribers?';
$lang_plugin_newsletter['remove_subscribers_explanation'] = 'This will permanently delete all subscriber records. The entire list of subscribers will be gone. This option will NOT touch your galler\'s users table.';
$lang_plugin_newsletter['newsletter_categories'] = 'Newsletter Categories';
$lang_plugin_newsletter['remove_categories'] = 'Delete newsletter categories?';
$lang_plugin_newsletter['remove_categories_explanation'] = 'This will permanently delete all newsletter categories.';
$lang_plugin_newsletter['mailings'] = 'Mailings';
$lang_plugin_newsletter['remove_mailings'] = 'Delete previous mailing records?';
$lang_plugin_newsletter['remove_mailings_explanation'] = 'This will permanently delete all newsletter mailings that you have ever sent. Of course this doesn\'t mean that the subscribers will notice.';
$lang_plugin_newsletter['mail_queue'] = 'Mail Queue';
$lang_plugin_newsletter['remove_queue'] = 'Cancel sending pending newsletters and delete mail queue?';
$lang_plugin_newsletter['remove_queue_explanation'] = 'There are still newsletter in the queue that are scheduled to be sent. Do you really want to cancel sending those emails and permanently delete the mail queue?';
$lang_plugin_newsletter['announcement_thread'] = 'Announcement thread';
$lang_plugin_newsletter['allow_guest_subscriptions'] = 'Allow guest subscriptions';
$lang_plugin_newsletter['salutation_for_guests'] = 'Salutation for guests';
$lang_plugin_newsletter['from_email'] = 'Email address used to send newsletter from';
$lang_plugin_newsletter['from_name'] = 'Name to send newsletter from';
$lang_plugin_newsletter['mails_per_page'] = 'Mails per page';
$lang_plugin_newsletter['administration_links'] = 'Display newsletter admin links in admin menu?';
$lang_plugin_newsletter['display_newsletter_in_menu_for_visitor'] = 'Display newsletter in menu for the regular visitor?';
$lang_plugin_newsletter['in_sys_menu'] = 'in Sys-Menu';
$lang_plugin_newsletter['in_sub_menu'] = 'in Sub-Menu';
$lang_plugin_newsletter['changes_saved'] = 'Your changes have been saved';
$lang_plugin_newsletter['no_changes'] = 'There have been no changes or the values you entered where invalid';
$lang_plugin_newsletter['submit_to_install'] = 'Submit this form to install the plugin';
$lang_plugin_newsletter['newsletter-subscription'] = 'Newsletter subscription';
$lang_plugin_newsletter['welcome_x'] = 'Welcome %s,';
$lang_plugin_newsletter['your_name'] = 'Your name';
$lang_plugin_newsletter['your_email'] = 'Your email address';
$lang_plugin_newsletter['not_allowed_to_subscribe'] = 'You\'re not allowed to subscribe.';
$lang_plugin_newsletter['alternatively_register_to subscribe'] = 'As an alternative to subscribing with your email address (as a guest), you could %sregister%s a user account and then subscribe easily as registered user.';
$lang_plugin_newsletter['register_to subscribe'] = 'To subscribe you need to %sregister%s a user account and then subscribe as registered user.';
$lang_plugin_newsletter['pluginmgr_lnk'] = 'Plugin Manager';
$lang_plugin_newsletter['email_address_invalid'] = 'Invalid email address';
$lang_plugin_newsletter['your_cant_edit_this_field'] = 'You can\'t edit the content of this field here, as it was taken from your profile. Edit your profile instead if you want to see this field\'s content changed.';
$lang_plugin_newsletter['email_from_profile'] = 'Email address taken from your %sprofile%s.';
$lang_plugin_newsletter['category_list'] = 'Newsletter category list';
$lang_plugin_newsletter['frequency_once_year'] = 'Once every year';
$lang_plugin_newsletter['frequency_twice_year'] = 'Twice a year';
$lang_plugin_newsletter['frequency_once_month'] = 'Once every month';
$lang_plugin_newsletter['frequency_twice_month'] = 'Twice every month';
$lang_plugin_newsletter['frequency_once_week'] = 'Weekly';
$lang_plugin_newsletter['frequency_once_day'] = 'Daily';
$lang_plugin_newsletter['frequency_x_times_per_year'] = '%s times a year';
$lang_plugin_newsletter['delete'] = 'Delete';
$lang_plugin_newsletter['name'] = 'Name';
$lang_plugin_newsletter['description'] = 'Description';
$lang_plugin_newsletter['open'] = 'Open';
$lang_plugin_newsletter['open_explanation'] = 'Open for subscription, i.e. visitors can subscribe to this category.';
$lang_plugin_newsletter['viewable'] = 'Viewable';
$lang_plugin_newsletter['viewable_explanation'] = 'Archives can be viewed publicly, i.e. visitors can browse previous mailings from that category before they subscribe.';
$lang_plugin_newsletter['frequency'] = 'Frequency';
$lang_plugin_newsletter['frequency_explanation'] = 'Determines the maximum number of mailings per period. This value is shown when the visitor subscribes, so you should respect it, as your subscribers will be upset if you send more emails than what you have specified here.';
$lang_plugin_newsletter['add'] = 'Add';
$lang_plugin_newsletter['changes_saved_for_category_x'] = 'Changes saved for category %s';
$lang_plugin_newsletter['category_x_created'] = 'Category %s created';
$lang_plugin_newsletter['category_x_deleted'] = 'Category %s deleted';
$lang_plugin_newsletter['mailings'] = 'Mailings';
$lang_plugin_newsletter['subscriptions'] = 'Subscriptions';
$lang_plugin_newsletter['subscribe_to'] = 'Subscribe to';
$lang_plugin_newsletter['subscribe'] = 'Subscribe';
$lang_plugin_newsletter['no_newsletter_to_subscribe_to'] = 'There are currently no newsletter that you could subscribe to.';
$lang_plugin_newsletter['browse_archived_mailings'] = 'Browse archived mailings';
$lang_plugin_newsletter['archive'] = 'Newsletter archive';
$lang_plugin_newsletter['sbuscription_updated'] = 'Your subscription has been updated';
$lang_plugin_newsletter['no_update_needed'] = 'No update needed';
$lang_plugin_newsletter['successfully_subscribed'] = 'You have successfully subscribed';
$lang_plugin_newsletter['you_have_unsubscribed'] = 'You have unsubscribed';
$lang_plugin_newsletter['at_least_one_category_needed'] = 'You need to subscribe at least to one category to receive mailings';
$lang_plugin_newsletter['edit_your_subscription'] = 'edit your subscription';
$lang_plugin_newsletter['no_email_in_profile'] = 'There is no email address set in your profile. Newsletter mailings won\'t work without an email address.';
?>