CREATE TABLE IF NOT EXISTS `CPG_mod_slider` (
  `slider_useenlarge` int(2) NOT NULL default '1',
  `slider_enlborder` int(2) NOT NULL default '1',
  `slider_enlbrdsize` int(2) NOT NULL default '1',
  `slider_enlbrdcolor` varchar(7) default '#000000',
  `slider_enlmaxstep` int(2) NOT NULL default '8',
  `slider_enlspeed` int(2) NOT NULL default '20',
  `slider_enlani` int(2) NOT NULL default '1',
  `slider_width` int(2) NOT NULL default '600',
  `slider_height` int(2) NOT NULL default '60',
  `slider_numberofpics` int(2) NOT NULL default '20',
  `slider_speed` int(2) NOT NULL default '1',
  `slider_bgcolor` varchar(7) default '',
  `slider_album` varchar(100) default 'random',
  `slider_skipportrait` int(2) NOT NULL default '0',
  `slider_align` varchar(15) default 'center',
  `slider_enlshadow` int(2) NOT NULL default '1',
  `slider_enlshadowsize` int(2) NOT NULL default '1',
  `slider_enlshadowintens` int(2) NOT NULL default '12',
  `slider_enlshowcap` int(2) NOT NULL default '1',
  `slider_pictype` varchar(100) default 'normal',
  `slider_enlclosebtn` int(2) NOT NULL default '1',
  `slider_enlcenter` int(2) NOT NULL default '1',
  `slider_enldark` int(2) NOT NULL default '1',
  `slider_autowidth` int(2) NOT NULL default '0'
);